#!/bin/sh

# jemalloc's configure runs git to determine the version. But when building
# from a goanna git clone, the git commands it uses is going to pick goanna's
# information, not jemalloc's, which is useless. So pretend we don't have git
# at all. That will make jemalloc's configure pick the in-tree VERSION file.

exit 1
